test
MateuszPapiez/Countries_app pull request #2
Opened 2022-12-09 10:31 UTC by MateuszPapiez

2022-12-09 10:50 UTC, Peterses approved these changes

2022-12-09 17:55 UTC, Peterses submitted a review, later dismissed

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                    List{
`List {`

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                Color("Background")
Please create new file and store colors defined by you in `enum` or `struct`.

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                                }
This is ok, but you are coping same code for different country. Please create new view, for example `CountryElement` and pass country name, capital and flag as a parameters of init.

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                        HStack{
`HStack {`

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                        HStack{
`HStack {`

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/CountryList.swift
> +    let flag_image: String
I know that's the preference but pls use in this project camel case while naming everything.

[https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference?amp=1](https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference?amp=1)

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/TestView.swift
> +        Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
What is it?

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/TestView.swift
> +
If you don't need that file pls remove it.

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/CountryList.swift
> +        //id: " ",
Don't leave commented code like that.

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/CountryList.swift
> +        //id: " ",
Don't leave commented code like that.

2022-12-09 17:55 UTC, Peterses commented on Countries_application/Countries_application/ContentView.swift
> +                                .font(.system(size: 32))
Maybe you don't need to specify the font size directly? See font sizes already defined in SwiftUI. 

[https://developer.apple.com/design/human-interface-guidelines/foundations/typography/](https://developer.apple.com/design/human-interface-guidelines/foundations/typography/)

[https://developer.apple.com/documentation/swiftui/font](https://developer.apple.com/documentation/swiftui/font)

You can use it like that:
For example:
`.font(.headline)`

2022-12-09 17:56 UTC, Peterses requested changes
Pls fix comments

2022-12-20 16:44 UTC, Peterses approved these changes

2022-12-20 16:45 UTC, MateuszPapiez commented
fix  error

2022-12-20 16:45 UTC, merged